FROM archlinux

LABEL version="0.2.0"
LABEL maintainer="haru"
LABEL name="timetable-backend-rust"

RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm rustup
RUN pacman -S --noconfirm git
RUN pacman -S --noconfirm clang
RUN pacman -S --noconfirm nano

RUN rustup default stable
RUN rustup component add rls rust-analysis rust-src

VOLUME /app
WORKDIR /app
